train: D:/VS Code Projects/TumAI/data/degpr_yolo_training_data/images/train/
val:  D:/VS Code Projects/TumAI/data/degpr_yolo_training_data/images/val/
test: D:/VS Code Projects/TumAI/data/degpr_yolo_training_data/images/test/

# number of classes
nc: 1

# class names
names: ["Neuron"]